# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  -
    main: main.go
    binary: pastebin
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - netbsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: openbsd
        goarch: arm
        goarm: 6
      - goos: freebsd
        goarch: arm
        goarm: 6
archives:
  - id: common
    name_template: "{{.Os}}-{{.Arch}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

